[package]
name = "mpi_config"
version = "0.1.0"
edition = "2021"

[dependencies]
arith = { path = "../../arith" }
mpi.workspace = true
itertools.workspace = true

[dev-dependencies]
ark-std.workspace = true
mersenne31 = { path = "../../arith/mersenne31"}
gf2 = { path = "../../arith/gf2" }
