[package]
name = "serdes"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
halo2curves.workspace = true
ethnum.workspace = true

serdes_derive = { path = "../serdes_derive" }

[dev-dependencies]
rand.workspace = true
