[package]
name = "gkr_hashers"
version.workspace = true
edition.workspace = true

[dependencies]
arith = { path = "../arith" }
serdes = { path = "../serdes" }


halo2curves.workspace = true
sha2.workspace = true
tiny-keccak.workspace = true
