[package]
name = "sumcheck"
version = "0.1.0"
edition = "2021"

[dependencies]
arith = { path = "../arith" }
circuit = { path = "../circuit" }
gkr_engine = { path = "../gkr_engine" }
polynomials = { path = "../arith/polynomials" }
transcript = { path = "../transcript" }
utils = { path = "../utils" }
serdes = { path = "../serdes" }

env_logger.workspace = true
log.workspace = true

[features]
profile = [ "utils/profile" ]
