[package]
name = "tree"
version = "0.1.0"
edition = "2021"

[dependencies]
arith = { path = "../arith" }
# babybear = { path = "../arith/babybear" }
# poseidon = { path = "../poseidon" }

ark-std.workspace = true
sha2.workspace = true
rayon.workspace = true

p3-baby-bear.workspace = true
p3-field.workspace = true
p3-monty-31.workspace = true